### ISSUE TITLE
Using classes with a service on controller breaks since version 0.7

### ISSUE THREAD

**Issue by BrookenRecord** [osyrisrblx/rbxts-knit#5]
We're currently blocked from upgrading `@rbxts/knit` past version 0.6 because our "class method" no longer works. There are no errors and Knit reports that everything has started properly, but nothing runs. I have tried to diff the version and have found nothing which could cause this.

Our service and controller definitions look like this:
```typescript
export const ExampleController = Knit.CreateController(
    new (class ExampleController extends KnitController {
        public Name = "ExampleController";

        public KnitStart() {}
    })(),
);
```

We do this because it is much easier to work in a class rather than an object (which is used by default).

I have gone into Knit's source and as far as I can tell, by the time that `Knit.Start()` runs, all services and controllers no longer have their methods or properties. Maybe there was a change introduced that removes the class metatable?

**Comment by osyrisrblx** [comment]
I suspect this is due to `Knit:CreateService()`/`Knit:CreateController()` using `TableUtil.Assign()` on the `service` argument.

As of `v0.0.16-alpha`, Knit's `TableUtil` functions are mostly immutable and return new values instead of modifying inputs. So Knit does a shallow copy of the input `service` which loses the metatable.

You might be able to hack this by doing:

**`patchKnit.lua`**
```lua
local function metatablePatcher(originalFunc)
	return function(obj)
		return setmetatable(originalFunc(obj), getmetatable(obj))
	end
end

local function patchKnitClient(KnitClient)
	KnitClient.CreateController = metatablePatcher(KnitClient.CreateController)
end

local function patchKnitServer(KnitServer)
	KnitServer.CreateService = metatablePatcher(KnitServer.CreateService)
end

return {
	patchKnitClient = patchKnitClient,
	patchKnitServer = patchKnitServer,
}
```

**`patchKnit.d.ts`**
```ts
import { KnitClient, KnitServer } from "@rbxts/knit";
export declare function patchKnitClient(KnitServer: KnitClient): void;
export declare function patchKnitServer(KnitServer: KnitServer): void;
```

**`main.server.ts`**
```ts
import { KnitServer as Knit } from "@rbxts/knit";
import { patchKnitServer } from "./patchKnit";

patchKnitServer(Knit);

// startup your services here..
declare const folder: Folder;
Knit.AddServices(folder);
```

(But I haven't tested this myself..)

**Comment by osyrisrblx** [comment]
Closing this for now since there's no actionable items for this repository. If you wanted a real fix, it'll have to happen upstream: https://github.com/Sleitnick/Knit/issues
